/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bai9_EmployeeManager;

import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author NGOC TY
 */
public class EmployeeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeJFrame
     */
    public EmployeeJFrame() {
        initComponents();
    }
    Manage man=new Manage();
    Employee emp=new Employee();
    OfficialEmployee official=new OfficialEmployee();
    ParttimeEmployee parttime=new ParttimeEmployee();
    Boolean checkExist=false;
    Boolean checkOfficial=false;
    Boolean checkParttime=false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfBirthday = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cbBoy = new javax.swing.JCheckBox();
        cbGirl = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        tfPhone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfSalary = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbOfficial = new javax.swing.JCheckBox();
        cbParttime = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EmployeeManager");

        jLabel1.setText("ID");

        tfID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfIDMouseClicked(evt);
            }
        });
        tfID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Birthday");

        tfBirthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBirthdayActionPerformed(evt);
            }
        });

        jLabel4.setText("Gender");

        cbBoy.setText("Boy");
        cbBoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBoyActionPerformed(evt);
            }
        });

        cbGirl.setText("Girl");
        cbGirl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGirlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbGirl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(cbBoy)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBoy)
                    .addComponent(cbGirl))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jLabel5.setText("Phone");

        tfPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPhoneActionPerformed(evt);
            }
        });

        jLabel6.setText("Address");

        jLabel7.setText("Salary");

        tfSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSalaryActionPerformed(evt);
            }
        });

        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        btUpdate.setText("Update");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        jLabel8.setText("EmployType");

        cbOfficial.setText("Official");
        cbOfficial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOfficialActionPerformed(evt);
            }
        });

        cbParttime.setText("Parttime");
        cbParttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbParttimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbOfficial)
                .addGap(41, 41, 41)
                .addComponent(cbParttime)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbOfficial)
                    .addComponent(cbParttime))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel8))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfID)
                            .addComponent(tfBirthday)
                            .addComponent(tfPhone)
                            .addComponent(tfSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfName)
                            .addComponent(tfAddress))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btAdd)
                .addGap(47, 47, 47)
                .addComponent(btDelete)
                .addGap(51, 51, 51)
                .addComponent(btUpdate)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(tfBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdd)
                    .addComponent(btDelete)
                    .addComponent(btUpdate))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setToDefaul(){
        man.officialList.clear();
        man.parttimeList.clear();
        checkExist=false;
        checkOfficial=false;
        checkParttime=false;
        tfID.setText("");
        tfAddress.setText("");
        tfBirthday.setText("");
        tfName.setText("");
        tfPhone.setText("");
        tfSalary.setText("");
        cbBoy.setSelected(false);
        cbGirl.setSelected(false);
        cbOfficial.setSelected(false);
        cbParttime.setSelected(false);
    }
    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        if(!checkExist){
          emp.employeeName=tfName.getText();
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        if(checkExist){
            if(checkOfficial){
                man.officialList.remove(official);
                try {
                    man.writeFileOfficialEmloyee();
                } catch (IOException ex) {
                    Logger.getLogger(EmployeeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if(checkParttime){
                man.parttimeList.remove(parttime);
                try {
                    man.writeFileParttimeEmployee();
                } catch (IOException ex) {
                    Logger.getLogger(EmployeeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btDeleteActionPerformed

    private void tfIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDActionPerformed
        try {
            man.readFileOfficialEmployee();
            man.readFileParttimeEmployee();
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(EmployeeJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        emp.employeeID=Integer.parseInt(tfID.getText());
        for(OfficialEmployee o: man.officialList){
            if(emp.employeeID==o.employeeID)
            {
                emp=o;
                official=o;
                tfName.setText(emp.employeeName);
                tfBirthday.setText(emp.birthday);
                tfAddress.setText(emp.address);
                tfPhone.setText(emp.phoneNumber);
                tfSalary.setText(String.valueOf(emp.salary));
                cbOfficial.setSelected(true);
                if("Nu".equals(emp.gender)){
                    cbGirl.setSelected(true);
                }
                else cbBoy.setSelected(true);
                checkExist=true;
                checkOfficial=true;
                break;
            }
        }
        if(!checkExist){
            for(ParttimeEmployee p:man.parttimeList){
                if(emp.employeeID==p.employeeID){
                    emp=p;
                    parttime=p;
                    checkParttime=true;
                    checkExist=true;
                    tfName.setText(emp.employeeName);
                    tfBirthday.setText(emp.birthday);
                    tfAddress.setText(emp.address);
                    tfPhone.setText(emp.phoneNumber);
                    tfSalary.setText(String.valueOf(emp.salary));
                    cbParttime.setSelected(true);
                    if("Nu".equals(emp.gender)){
                        cbGirl.setSelected(true);
                    }
                    else cbBoy.setSelected(true);   
                    break;
                }
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDActionPerformed

    private void cbOfficialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOfficialActionPerformed
        if(!checkExist){
            if(cbOfficial.isSelected()){
                cbParttime.setSelected(false);
                checkParttime=false;
                checkOfficial=true;
            }
        }
        else{
            if(checkOfficial){
                cbOfficial.setSelected(true);
                cbParttime.setSelected(false);
            }
            else if(checkParttime){
                cbOfficial.setSelected(false);
                cbParttime.setSelected(true);
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_cbOfficialActionPerformed

    private void tfIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfIDMouseClicked
        setToDefaul();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDMouseClicked

    private void tfBirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBirthdayActionPerformed
        emp.birthday=tfBirthday.getText();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBirthdayActionPerformed

    private void cbGirlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGirlActionPerformed
        if(cbGirl.isSelected()){
            emp.gender="Nu";
            cbBoy.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGirlActionPerformed

    private void tfPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPhoneActionPerformed
        emp.phoneNumber=tfPhone.getText();
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPhoneActionPerformed

    private void cbBoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBoyActionPerformed
        if(cbBoy.isSelected()){
            emp.gender="Nam";
            cbGirl.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBoyActionPerformed

    private void cbParttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbParttimeActionPerformed
        if(!checkExist){
            if(cbParttime.isSelected()){
                cbOfficial.setSelected(false);
                checkParttime=true;
                checkOfficial=false;
            }

        }
        else{
            if(checkOfficial){
                cbOfficial.setSelected(true);
                cbParttime.setSelected(false);
            }
            else if(checkParttime){
                cbOfficial.setSelected(false);
                cbParttime.setSelected(true);
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_cbParttimeActionPerformed

    private void tfSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSalaryActionPerformed
        emp.salary=Float.parseFloat(tfSalary.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSalaryActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        if(!checkExist){
            if(checkOfficial)
            {
                official.address=emp.address;
                official.birthday=emp.address;
                official.employeeID=emp.employeeID;
                official.employeeName=emp.employeeName;
                official.gender=emp.gender;
                official.phoneNumber=emp.phoneNumber;
                official.salary=emp.salary;
                man.officialList.add(official);
                try {
                    man.writeFileOfficialEmloyee();
                } catch (IOException ex) {
                    Logger.getLogger(EmployeeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if(checkParttime){
                parttime.address=emp.address;
                parttime.birthday=emp.address;
                parttime.employeeID=emp.employeeID;
                parttime.employeeName=emp.employeeName;
                parttime.gender=emp.gender;
                parttime.phoneNumber=emp.phoneNumber;
                parttime.salary=emp.salary;
                man.parttimeList.add(parttime);
                try {
                    man.writeFileParttimeEmployee();
                } catch (IOException ex) {
                    Logger.getLogger(EmployeeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        setToDefaul();
        // TODO add your handling code here:
    }//GEN-LAST:event_btAddActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        if(checkExist){
            if(checkOfficial){
                for(OfficialEmployee o:man.officialList){
                    if(official.employeeID==o.employeeID){
                        o=official;
                        try {
                            man.writeFileOfficialEmloyee();
                        } catch (IOException ex) {
                            Logger.getLogger(EmployeeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        break;
                    }
                }
            }
            if(checkParttime){
                for(ParttimeEmployee p: man.parttimeList){
                    if(parttime.employeeID==p.employeeID){
                        p=parttime;
                        try {
                            man.writeFileParttimeEmployee();
                        } catch (IOException ex) {
                            Logger.getLogger(EmployeeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        break;
                    }
                }
            }
            
        }
        setToDefaul();
        // TODO add your handling code here:
    }//GEN-LAST:event_btUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btUpdate;
    private javax.swing.JCheckBox cbBoy;
    private javax.swing.JCheckBox cbGirl;
    private javax.swing.JCheckBox cbOfficial;
    private javax.swing.JCheckBox cbParttime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfBirthday;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPhone;
    private javax.swing.JTextField tfSalary;
    // End of variables declaration//GEN-END:variables
}
